-- Query 3 of 3: create small searchable/vector pieces under each article.
-- The full vector coordinate is (year, month, article_index, chunk_index).

begin;

create extension if not exists vector;

create table if not exists smaller_chunks (
  year integer not null,
  month smallint not null,
  article_index integer not null,
  chunk_index integer not null check (chunk_index >= 0),
  id bigint generated by default as identity unique,
  content text not null,
  embedding vector(1536) not null,
  created_at timestamptz not null default now(),
  primary key (year, month, article_index, chunk_index),
  foreign key (year, month, article_index)
    references articles (year, month, article_index)
    on update cascade
    on delete cascade
);

do $$
begin
  if to_regclass('public.chunks_legacy') is not null
     and to_regclass('public.articles_legacy') is not null then
    execute $migration$
      insert into smaller_chunks (
        year,
        month,
        article_index,
        chunk_index,
        id,
        content,
        embedding
      )
      select
        a.issue_year,
        a.issue_month_number,
        a.article_index,
        c.chunk_index,
        c.id,
        c.content,
        c.embedding
      from chunks_legacy c
      join articles_legacy a on a.id = c.article_id
      order by
        a.issue_year,
        a.issue_month_number,
        a.article_index,
        c.chunk_index
      on conflict (year, month, article_index, chunk_index) do nothing
    $migration$;
  end if;
end
$$;

select setval(
  pg_get_serial_sequence('smaller_chunks', 'id'),
  coalesce((select max(id) from smaller_chunks), 0) + 1,
  false
);

create index if not exists smaller_chunks_embedding_hnsw_idx
  on smaller_chunks using hnsw (embedding vector_cosine_ops);

commit;

select
  year,
  month,
  article_index,
  chunk_index,
  id,
  left(content, 100) as content_preview
from smaller_chunks
order by year, month, article_index, chunk_index
limit 200;
