-- Query 2 of 3: create articles under each monthly Sampada.
-- The chronological identity is (year, month, article_index).

begin;

create table if not exists articles (
  year integer not null,
  month smallint not null,
  article_index integer not null check (article_index >= 1),
  id bigint generated by default as identity,
  article_title text not null,
  author text,
  body text not null,
  source_url text,
  source_pdf_id text not null,
  content_type text not null default 'text',
  created_at timestamptz not null default now(),
  constraint articles_coordinate_pkey
    primary key (year, month, article_index),
  constraint articles_id_unique unique (id),
  constraint articles_sampada_fkey foreign key (year, month)
    references sampada (year, month)
    on update cascade
    on delete cascade
);

do $$
begin
  if to_regclass('public.articles_legacy') is not null then
    execute $migration$
      insert into articles (
        year,
        month,
        article_index,
        id,
        article_title,
        author,
        body,
        source_url,
        source_pdf_id,
        content_type,
        created_at
      )
      select
        issue_year,
        issue_month_number,
        article_index,
        id,
        article_title,
        author,
        body,
        source_url,
        drive_file_id,
        content_type,
        created_at
      from articles_legacy
      order by issue_year, issue_month_number, article_index
      on conflict (year, month, article_index) do nothing
    $migration$;
  end if;
end
$$;

-- Advance the identity sequence beyond any IDs preserved from the old table.
select setval(
  pg_get_serial_sequence('articles', 'id'),
  coalesce((select max(id) from articles), 0) + 1,
  false
);

commit;

select year, month, article_index, id, article_title
from articles
order by year, month, article_index;
