create extension if not exists vector;

-- One Sampada publication per calendar month.
create table sampada (
  year integer not null check (year between 1945 and 2017),
  month smallint not null check (month between 1 and 12),
  source_pdf_id text not null,
  source_url text,
  created_at timestamptz not null default now(),
  primary key (year, month)
);

-- Articles are addressed chronologically by (year, month, article_index).
-- `id` remains as a stable public identifier for URLs and citations.
create table articles (
  year integer not null,
  month smallint not null,
  article_index integer not null check (article_index >= 1),
  id bigint generated by default as identity,
  article_title text not null,
  author text,
  body text not null,
  source_url text,
  source_pdf_id text not null,
  content_type text not null default 'text',
  created_at timestamptz not null default now(),
  constraint articles_coordinate_pkey
    primary key (year, month, article_index),
  constraint articles_id_unique unique (id),
  constraint articles_sampada_fkey foreign key (year, month)
    references sampada (year, month)
    on update cascade
    on delete cascade
);

-- Searchable vector pieces are addressed by the complete archive coordinate.
create table smaller_chunks (
  year integer not null,
  month smallint not null,
  article_index integer not null,
  chunk_index integer not null check (chunk_index >= 0),
  id bigint generated by default as identity unique,
  content text not null,
  embedding vector(1536) not null,
  created_at timestamptz not null default now(),
  primary key (year, month, article_index, chunk_index),
  foreign key (year, month, article_index)
    references articles (year, month, article_index)
    on update cascade
    on delete cascade
);

create index articles_chronology_idx
  on articles (year, month, article_index);

create index smaller_chunks_embedding_hnsw_idx
  on smaller_chunks using hnsw (embedding vector_cosine_ops);
